import { ClipboardCheck, FileQuestion, Info } from "lucide-react";
import { Breadcrumbs } from "@/components/ui/breadcrumbs";
import { ButtonLink } from "@/components/ui/button-link";
import { Container } from "@/components/ui/container";
import type { Service } from "@/types/content";

export function ServicePage({ service }: { service: Service }) {
  return <><section className="internal-hero"><Container><Breadcrumbs items={[{ label: "Esami e valutazioni", href: "/esami" }, { label: service.title }]} /><div className="internal-hero-grid"><div><p className="eyebrow">Esame o valutazione</p><h1>{service.title}</h1><p className="internal-lead">{service.description}</p><ButtonLink href="/prenota">Prenota una visita</ButtonLink></div><aside className={service.availabilityConfirmed ? "availability-note availability-note--confirmed" : "availability-note"}><Info aria-hidden="true" /><div><strong>{service.availabilityConfirmed ? "Prestazione confermata" : "Disponibilità da verificare"}</strong><p>{service.availabilityConfirmed ? "La prestazione è disponibile presso la sede indicata. Contatta lo studio per la prenotazione." : "Questa prestazione non è ancora presentata come prenotabile e sarà aggiornata dopo conferma."}</p></div></aside></div></Container></section><section className="section"><Container className="service-detail"><section><p className="eyebrow">A cosa serve</p><h2>Il ruolo nel percorso</h2><p>{service.purpose}</p></section><section><ClipboardCheck aria-hidden="true" /><h2>Come può svolgersi</h2><ul className="check-list">{service.whatToExpect.map((item) => <li key={item}>{item}</li>)}</ul></section><section><FileQuestion aria-hidden="true" /><h2>Come prepararsi</h2><ul className="check-list">{service.preparation.map((item) => <li key={item}>{item}</li>)}</ul></section>{service.references?.length ? <section className="sources"><h2>Fonti informative</h2>{service.references.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.label}</a>)}</section> : null}<aside className="medical-disclaimer">Le indicazioni sono generali. Preparazione, appropriatezza e modalità effettive dipendono dal quesito clinico e dalla sede.</aside></Container></section><section className="topic-cta"><Container><h2>Non sai quale valutazione sia adatta?</h2><p>La scelta degli esami dovrebbe partire dal problema clinico, non dall’esame stesso.</p><ButtonLink href="/prenota">Prenota una visita</ButtonLink></Container></section></>;
}
