import type { Metadata } from "next";
import { CalendarDays, ExternalLink, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { Breadcrumbs } from "@/components/ui/breadcrumbs";
import { Container } from "@/components/ui/container";
import { siteConfig } from "@/config/site";
import { locations } from "@/data/locations";

export const metadata: Metadata = { title: "Prenota una visita", description: "Prenota online una visita pneumologica con il Dr. Simone Contino a Milano tramite Google Calendar, WhatsApp o email." };

export default function BookingPage() {
  const location = locations[0];
  return <><section className="booking-page-hero"><Container><Breadcrumbs items={[{ label: "Prenota una visita" }]} /><div><p className="eyebrow">Il prossimo passo</p><h1>Prenota una visita</h1><p className="internal-lead">Scegli direttamente giorno e orario disponibili nell’agenda online. Per richieste organizzative puoi utilizzare anche WhatsApp o email.</p></div></Container></section><section className="section"><Container className="booking-options"><article className="booking-primary"><CalendarDays aria-hidden="true" /><span className="booking-ready-badge">Agenda disponibile</span><h2>Fissa un appuntamento online</h2><p>Consulta le disponibilità aggiornate e scegli l’appuntamento tramite Google Calendar.</p><a className="button button--light" href={siteConfig.bookingUrl} target="_blank" rel="noreferrer">Apri l’agenda <ExternalLink aria-hidden="true" /></a><small>Il link si apre in una nuova scheda su Google Calendar.</small></article><div className="booking-contact-list"><article><MessageCircle aria-hidden="true" /><div><h3>WhatsApp Business</h3><a href={siteConfig.whatsappUrl} target="_blank" rel="noreferrer">{siteConfig.whatsapp}</a></div></article><article><Phone aria-hidden="true" /><div><h3>Telefono</h3><a href={siteConfig.phoneHref}>{siteConfig.phone}</a></div></article><article><Mail aria-hidden="true" /><div><h3>Email professionale</h3><a href={siteConfig.emailHref}>{siteConfig.email}</a></div></article><article><MapPin aria-hidden="true" /><div><h3>Sede</h3><p>{location.name}<br />{location.address}, {location.postalCode} {location.city}</p><a href={location.mapsUrl} target="_blank" rel="noreferrer">Apri in Google Maps</a></div></article></div></Container></section><section className="booking-safety"><Container><h2>Informazioni pratiche</h2><div><p><strong>Non serve l’impegnativa.</strong> La prima visita dura indicativamente 45 minuti; il controllo 30–40 minuti.</p><p><strong>Cosa portare:</strong> cartella clinica completa e imaging toracico disponibile. Gli esami possono essere consegnati fisicamente o tramite email.</p><p><strong>Questo sito non gestisce emergenze.</strong> In caso di grave difficoltà respiratoria o altri sintomi urgenti, chiama il 112.</p></div></Container></section></>;
}
