import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CircleGauge, MoonStar, Wind } from "lucide-react";
import { Breadcrumbs } from "@/components/ui/breadcrumbs";
import { ButtonLink } from "@/components/ui/button-link";
import { Container } from "@/components/ui/container";
import { ContentStatus } from "@/components/ui/content-status";

export const metadata: Metadata = { title: "Disturbi respiratori del sonno", description: "Russamento, apnee ostruttive, sonnolenza, poligrafia respiratoria e CPAP: informazioni sul percorso di valutazione a Milano." };
const routes = [
  { title: "Russamento", text: "Capire quando è un fenomeno isolato e quando può accompagnarsi a pause respiratorie.", href: "/problemi/russamento", icon: MoonStar },
  { title: "Apnee ostruttive", text: "Riconoscere i segnali notturni e diurni e comprendere il percorso diagnostico.", href: "/patologie/apnee-ostruttive-sonno", icon: Wind },
  { title: "Sonnolenza diurna", text: "Distinguere sonnolenza e stanchezza e valutarne l’impatto sulla sicurezza.", href: "/problemi/sonnolenza-diurna", icon: CircleGauge },
];
export default function SleepPage() { return <><section className="sleep-hero"><Container><Breadcrumbs items={[{ label: "Disturbi respiratori del sonno" }]} /><div className="sleep-hero-grid"><div><p className="eyebrow">Un’area distintiva della pneumologia</p><h1>Respirare bene anche durante il sonno.</h1><p className="internal-lead">Russamento, pause respiratorie e sonnolenza possono essere segnali di un disturbo respiratorio notturno. Comprenderli richiede una valutazione che tenga insieme sonno, respiro e salute generale.</p><ButtonLink href="/prenota">Prenota una visita</ButtonLink></div><ContentStatus /></div></Container></section><section className="section"><Container><div className="sleep-intro"><div><p className="eyebrow">Da dove partire</p><h2>Non tutto il russamento è apnea. Non tutta la stanchezza dipende dal sonno.</h2></div><p>Il percorso inizia distinguendo i sintomi, il loro impatto e i fattori di rischio. Solo dopo questa valutazione si decide se uno studio respiratorio del sonno sia appropriato.</p></div><div className="sleep-route-grid">{routes.map(({ icon: Icon, ...item }) => <Link href={item.href} key={item.href}><Icon aria-hidden="true" /><h3>{item.title}</h3><p>{item.text}</p><span>Approfondisci <ArrowRight aria-hidden="true" /></span></Link>)}</div></Container></section><section className="section section--tint"><Container><div className="sleep-steps"><div><span>01</span><h3>Valutazione clinica</h3><p>Sintomi notturni e diurni, qualità del sonno, farmaci, patologie associate e impatto quotidiano.</p></div><div><span>02</span><h3>Studio del sonno, se indicato</h3><p>Poligrafia respiratoria o altri approfondimenti vengono scelti in base al quesito clinico. Disponibilità da confermare.</p></div><div><span>03</span><h3>Scelta del trattamento</h3><p>Gli interventi dipendono dalla diagnosi, dalla gravità e dalle caratteristiche della persona.</p></div><div><span>04</span><h3>Adattamento e follow-up</h3><p>Se viene prescritta una CPAP, comfort, utilizzo e risposta clinica vanno rivalutati nel tempo. Servizio da confermare.</p></div></div></Container></section><section className="topic-cta"><Container><h2>Il sonno racconta anche come respiri.</h2><p>Una valutazione può aiutare a mettere in ordine sintomi notturni, stanchezza e fattori di rischio.</p><ButtonLink href="/prenota">Prenota una visita</ButtonLink></Container></section></>;
}
